spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/projetojpa?useTimezone=true?serverTimezone=UTC
    username: caioh
    password: projetojpa
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false
springdoc:
  swagger-ui:
    use-root-path: true
  paths-to-match: /**/v1/**
